name: Get latest pihole release, build it and push to dockerhub

on:
  # cron job to trigger the build on any push to main
  push:
    branches:
      - 'main'
  schedule:
  # cron job to trigger the build daily
    - cron:  '0 0 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get latest release of pihole docker container
      id: pihole_version
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
        type: "stable"
      run: |
        pihole_version=$(curl --silent "https://api.github.com/repos/pi-hole/docker-pi-hole/releases/latest")
        echo "release=$(echo $pihole_version | jq -r '.tag_name')" >> $GITHUB_OUTPUT
        echo ${{ steps.pihole_version.outputs.release }}

    - name: check if release is new
      id: check_release
      run: |
        if [ "${{ steps.pihole_version.outputs.release }}" != "${{ github.event.before }}" ]
        then
          echo "new_release='true'" >> $GITHUB_OUTPUT
        else
          echo "new_release='false'" >> $GITHUB_OUTPUT
        fi
        echo ${{ steps.pihole_version.outputs.new_release }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      if: steps.check_release.outputs.new_release == 'true'
      with:
        build-args: PIHOLE_VERSION=${{ steps.pihole_version.outputs.release }}
        context: "{{defaultContext}}:pihole-unbound/"
        platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
        push: true
        tags: liblame/pihole-unbound:latest,liblame/pihole-unbound:${{ steps.pihole_version.outputs.release }}
